### ISSUE TITLE
Failed to download repo due to missing submodule URL

### ISSUE THREAD

**Issue by ChrisTimperley** [gaoxiang9430/Fix2Fit#2]
```
$ git clone git@github.com:gaoxiang9430/Fix2Fit
...
$ git submodule update --init --recursive
fatal: No url found for submodule path 'projects/proj4_1793/proj4' in .gitmodules
```

**Comment by joaofcmb** [comment]
I had the same issue. It seems like `projects/proj4_1793/proj4` was added as a submodule, yet there is no .gitmodules entry specifying it. Running `git rm projects/proj4_1793/proj4` circumvents this issue by removing the submodule

**Comment by gaoxiang9430** [comment]
Thanks, I have fixed this issue.
